import { useEffect, useMemo, useState } from 'react'
import { Button } from '../../components/ui/Button'
import { Drawer } from '../../components/ui/Drawer'
import type { FocusSessionPreview, TaskPreview } from '../../types/ui'

function localDateTimeParts(value:string){const date=new Date(value);return {date:[date.getFullYear(),String(date.getMonth()+1).padStart(2,'0'),String(date.getDate()).padStart(2,'0')].join('-'),time:`${String(date.getHours()).padStart(2,'0')}:${String(date.getMinutes()).padStart(2,'0')}`}}
function toIso(date:string,time:string){const parsed=new Date(`${date}T${time}:00`);if(!Number.isFinite(parsed.getTime()))throw new Error('Invalid date/time.');return parsed.toISOString()}
function formatMinutes(seconds:number){const min=Math.round(seconds/60),h=Math.floor(min/60),m=min%60;return h?`${h}h${m?` ${m}m`:''}`:`${m}m`}
function tags(value:string){return [...new Set(value.split(',').map((item)=>item.trim()).filter(Boolean))].slice(0,30)}

export function FocusHistoryDrawer({open,sessions,tasks,dailyTrend,projectBreakdown,taskBreakdown,goals,weekSeconds,todaySeconds,interruptionCount,manualWeekSeconds,onClose,onSetGoals,onAddManual,onEdit,onDelete}:{open:boolean;sessions:FocusSessionPreview[];tasks:TaskPreview[];dailyTrend:Array<{date:string;seconds:number}>;projectBreakdown:Array<{id:string;name:string;seconds:number}>;taskBreakdown:Array<{id:string;name:string;seconds:number;estimateMinutes?:number}>;goals:{dailyMinutes:number;weeklyMinutes:number};weekSeconds:number;todaySeconds:number;interruptionCount:number;manualWeekSeconds:number;onClose:()=>void;onSetGoals:(daily:number,weekly:number)=>Promise<void>;onAddManual:(input:{taskId?:string;startedAt:string;durationSeconds:number;note?:string;context?:string;tags?:string[];interruptionCount?:number})=>Promise<void>;onEdit:(id:string,input:{taskId?:string|null;startedAt?:string;durationSeconds?:number;note?:string|null;context?:string|null;tags?:string[];interruptionCount?:number})=>Promise<void>;onDelete:(id:string)=>Promise<void>}){
  const now=new Date()
  const defaultDate=[now.getFullYear(),String(now.getMonth()+1).padStart(2,'0'),String(now.getDate()).padStart(2,'0')].join('-')
  const defaultTime=`${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}`
  const [daily,setDaily]=useState(goals.dailyMinutes),[weekly,setWeekly]=useState(goals.weeklyMinutes)
  const [taskId,setTaskId]=useState(''),[date,setDate]=useState(defaultDate),[time,setTime]=useState(defaultTime),[duration,setDuration]=useState(30),[context,setContext]=useState(''),[tagText,setTagText]=useState(''),[note,setNote]=useState('')
  const [editingId,setEditingId]=useState<string|null>(null)
  const [editTaskId,setEditTaskId]=useState(''),[editDate,setEditDate]=useState(defaultDate),[editTime,setEditTime]=useState(defaultTime),[editDuration,setEditDuration]=useState(30),[editContext,setEditContext]=useState(''),[editTags,setEditTags]=useState(''),[editNote,setEditNote]=useState(''),[editInterruptions,setEditInterruptions]=useState(0)
  const [query,setQuery]=useState(''),[source,setSource]=useState<'all'|'timer'|'manual'>('all'),[error,setError]=useState('')
  useEffect(()=>{setDaily(goals.dailyMinutes);setWeekly(goals.weeklyMinutes)},[goals.dailyMinutes,goals.weeklyMinutes])
  const filtered=useMemo(()=>sessions.filter((session)=>(source==='all'||session.source===source)&&(!query.trim()||[session.taskTitle,session.projectName,session.context,...(session.tags??[])].filter(Boolean).join(' ').toLowerCase().includes(query.trim().toLowerCase()))),[sessions,source,query])
  const maxTrend=Math.max(1,...dailyTrend.map((row)=>row.seconds))
  const maxProject=Math.max(1,...projectBreakdown.map((row)=>row.seconds))

  function beginEdit(session:FocusSessionPreview){const parts=localDateTimeParts(session.startedAt);setEditingId(session.id);setEditTaskId(session.taskId??'');setEditDate(parts.date);setEditTime(parts.time);setEditDuration(Math.max(1,Math.round(session.durationSeconds/60)));setEditContext(session.context??'');setEditTags((session.tags??[]).join(', '));setEditNote(session.note??'');setEditInterruptions(session.interruptionCount??0);setError('')}

  async function addManual(event:React.FormEvent){event.preventDefault();setError('');try{await onAddManual({taskId:taskId||undefined,startedAt:toIso(date,time),durationSeconds:Math.max(1,duration)*60,note:note.trim()||undefined,context:context.trim()||undefined,tags:tags(tagText)});setNote('');setContext('');setTagText('')}catch(reason){setError(reason instanceof Error?reason.message:'Could not add time entry.')}}
  async function saveEdit(){if(!editingId)return;setError('');try{await onEdit(editingId,{taskId:editTaskId||null,startedAt:toIso(editDate,editTime),durationSeconds:Math.max(1,editDuration)*60,note:editNote.trim()||null,context:editContext.trim()||null,tags:tags(editTags),interruptionCount:Math.max(0,editInterruptions)});setEditingId(null)}catch(reason){setError(reason instanceof Error?reason.message:'Could not edit session.')}}

  return <Drawer open={open} title="Focus time log & analytics" onClose={onClose}><div className="focus-history-v2">
    <section className="focus-analytics-summary"><div><strong>{formatMinutes(todaySeconds)}</strong><span>Today / {daily}m goal</span></div><div><strong>{formatMinutes(weekSeconds)}</strong><span>Week / {weekly}m goal</span></div><div><strong>{interruptionCount}</strong><span>Interruptions this week</span></div><div><strong>{formatMinutes(manualWeekSeconds)}</strong><span>Manual logs this week</span></div></section>
    <section className="focus-history-section"><div className="section-title-row"><span className="eyebrow">Focus goals</span><em>Guidance only</em></div><div className="focus-goal-editor"><label>Daily <input type="number" min="0" max="1440" value={daily} onChange={(e)=>setDaily(Math.max(0,Number(e.target.value)||0))}/><span>min</span></label><label>Weekly <input type="number" min="0" max="10080" value={weekly} onChange={(e)=>setWeekly(Math.max(0,Number(e.target.value)||0))}/><span>min</span></label><Button onClick={()=>void onSetGoals(daily,weekly)}>Save goals</Button></div></section>
    <section className="focus-history-section"><div className="section-title-row"><span className="eyebrow">14-day focus</span><em>Focused work only</em></div><div className="focus-daily-trend">{dailyTrend.map((row)=><div key={row.date} title={`${row.date}: ${formatMinutes(row.seconds)}`}><i style={{height:`${Math.max(4,(row.seconds/maxTrend)*100)}%`}}/><span>{row.date.slice(-2)}</span></div>)}</div></section>
    <section className="focus-history-section focus-breakdowns"><div><div className="section-title-row"><span className="eyebrow">Projects · this week</span></div>{projectBreakdown.slice(0,8).map((row)=><div className="focus-breakdown-row" key={row.id}><span>{row.name}</span><i><b style={{width:`${(row.seconds/maxProject)*100}%`}}/></i><em>{formatMinutes(row.seconds)}</em></div>)}</div><div><div className="section-title-row"><span className="eyebrow">Tasks · actual vs estimate</span></div>{taskBreakdown.slice(0,8).map((row)=><div className="focus-task-breakdown" key={row.id}><strong>{row.name}</strong><span>{formatMinutes(row.seconds)} actual{row.estimateMinutes?` · ${row.estimateMinutes}m estimate · ${Math.round(row.seconds/60/row.estimateMinutes*100)}%`:''}</span></div>)}</div></section>
    <section className="focus-history-section"><div className="section-title-row"><span className="eyebrow">Manual time entry</span><em>Work tracked outside Folio</em></div><form className="focus-manual-form" onSubmit={addManual}><label><span>Task</span><select value={taskId} onChange={(e)=>setTaskId(e.target.value)}><option value="">No task</option>{tasks.map((task)=><option value={task.id} key={task.id}>{task.title}</option>)}</select></label><label><span>Date</span><input type="date" value={date} onChange={(e)=>setDate(e.target.value)}/></label><label><span>Start</span><input type="time" value={time} onChange={(e)=>setTime(e.target.value)}/></label><label><span>Duration</span><input type="number" min="1" max="1440" value={duration} onChange={(e)=>setDuration(Math.max(1,Number(e.target.value)||1))}/></label><label><span>Context</span><input value={context} onChange={(e)=>setContext(e.target.value)} /></label><label><span>Tags</span><input value={tagText} onChange={(e)=>setTagText(e.target.value)} /></label><label className="focus-manual-note"><span>Note</span><textarea rows={2} value={note} onChange={(e)=>setNote(e.target.value)}/></label><Button type="submit" variant="primary">Add time</Button></form></section>
    <section className="focus-history-section"><div className="section-title-row"><span className="eyebrow">Session history</span><em>{filtered.length} records</em></div><div className="focus-history-filters"><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search task, project, context, tag…"/><select value={source} onChange={(e)=>setSource(e.target.value as typeof source)}><option value="all">All sources</option><option value="timer">Timer</option><option value="manual">Manual</option></select></div><div className="focus-session-log">{filtered.slice(0,80).map((session)=><article key={session.id}>{editingId===session.id?<div className="focus-session-edit"><select value={editTaskId} onChange={(e)=>setEditTaskId(e.target.value)}><option value="">No task</option>{tasks.map((task)=><option value={task.id} key={task.id}>{task.title}</option>)}</select><input type="date" value={editDate} onChange={(e)=>setEditDate(e.target.value)}/><input type="time" value={editTime} onChange={(e)=>setEditTime(e.target.value)}/><input type="number" min="1" value={editDuration} onChange={(e)=>setEditDuration(Math.max(1,Number(e.target.value)||1))}/><input value={editContext} onChange={(e)=>setEditContext(e.target.value)} placeholder="Context"/><input value={editTags} onChange={(e)=>setEditTags(e.target.value)} placeholder="Tags"/><input type="number" min="0" value={editInterruptions} onChange={(e)=>setEditInterruptions(Math.max(0,Number(e.target.value)||0))} title="Interruptions"/><textarea value={editNote} onChange={(e)=>setEditNote(e.target.value)} placeholder="Note"/><div><Button variant="primary" onClick={()=>void saveEdit()}>Save</Button><Button onClick={()=>setEditingId(null)}>Cancel</Button></div></div>:<><div><strong>{session.taskTitle}</strong><span>{session.projectName??'No project'} · {session.source==='manual'?'Manual':'Timer'} · {new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(session.startedAt))}</span>{session.context?<small>{session.context}</small>:null}{session.tags?.length?<div className="focus-log-tags">{session.tags.map((tag)=><em key={tag}>#{tag}</em>)}</div>:null}</div><div><strong>{formatMinutes(session.durationSeconds)}</strong><span>{session.interruptionCount??0} interruptions</span><div><button onClick={()=>beginEdit(session)}>Edit</button><button onClick={()=>{if(window.confirm('Delete this focus session?'))void onDelete(session.id)}}>Delete</button></div></div></>}</article>)}</div></section>
    {error?<div className="form-error">{error}</div>:null}
  </div></Drawer>
}
