import type { HabitEntity, ProjectEntity, RecurringSeriesEntity, TaskEntity, TimeBlockEntity } from '../../domain/models'
import { localDateFromIso, minuteOfDayFromIso, durationMinutes } from '../planner/calendarLogic'

export function buildPatchInstructions(context: { projects: ProjectEntity[]; tasks: TaskEntity[]; habits: HabitEntity[]; timeBlocks: TimeBlockEntity[]; recurringSeries: RecurringSeriesEntity[] }, timezone = Intl.DateTimeFormat().resolvedOptions().timeZone || 'local') {
  const projects = context.projects.filter((item) => !item.archived).map((item) => ({ id: item.id, updatedAt: item.updatedAt, name: item.name, description: item.description, color: item.color, icon: item.icon, type: item.type, favorite: item.favorite, examDate: item.examDate, weeklyTargetMinutes: item.weeklyTargetMinutes }))
  const tasks = context.tasks.filter((item) => !item.deletedAt && item.status !== 'cancelled').map((item) => ({ id: item.id, updatedAt: item.updatedAt, title: item.title, description: item.description, status: item.status, projectId: item.projectId, parentTaskId: item.parentTaskId, priority: item.priority, plannedDate: item.plannedDate, deadline: item.deadline, estimatedMinutes: item.estimatedMinutes, seriesId: item.seriesId, recurrenceDate: item.recurrenceDate }))
  const habits = context.habits.filter((item) => !item.archived).map((item) => ({ id: item.id, updatedAt: item.updatedAt, title: item.title, description: item.description, kind: item.kind, target: item.target, schedule: item.schedule, countsTowardCapacity: item.countsTowardCapacity }))
  const timeBlocks = context.timeBlocks.map((item) => ({ id: item.id, updatedAt: item.updatedAt, kind: item.kind, taskId: item.taskId, title: item.title, date: localDateFromIso(item.start), startMinute: minuteOfDayFromIso(item.start), durationMinutes: durationMinutes(item.start, item.end) }))
  const recurringSeries = context.recurringSeries.filter((item) => item.status !== 'archived').map((item) => ({ id: item.id, updatedAt: item.updatedAt, title: item.title, status: item.status, startDate: item.startDate, rule: item.rule, taskTemplate: item.taskTemplate }))

  return `You are preparing a safe structured PATCH for Folio. Return ONLY valid JSON.\n\nProtocol:\n- format: "folio-patch"\n- version: 1\n- timezone: "${timezone}"\n- operations: ordered CREATE / UPDATE / DELETE operations.\n- UPDATE and DELETE MUST use the exact stable id and exact ifUpdatedAt shown in the context below. If unsure, do not target it.\n- Never invent existing IDs or timestamps. Never fuzzy-match.\n- CREATE uses a short local value.ref. Same-patch Tasks may use projectRef/taskRef to point to same-patch creates.\n- UPDATE never changes database IDs, createdAt/updatedAt, completion history, Focus history, Habit history, recurrenceDate, series ownership, or provenance.\n- Task UPDATE may change title, description, project, priority, status todo|inbox, plannedDate, deadline, estimate. It may NOT mark a Task completed.\n- DELETE is domain-safe: Task→Trash, Project/Habit→Archive, Recurring Series→End, Time Block→remove.\n- Dates are YYYY-MM-DD. startMinute is minutes after local midnight. Time Blocks may not cross midnight.\n- Recurring Series structural changes are rejected when future occurrences contain manual overrides.\n- Unknown fields are rejected.\n\nRoot shape:\n{\n  "format":"folio-patch",\n  "version":1,\n  "title":"…",\n  "timezone":"${timezone}",\n  "operations":[]\n}\n\nExamples:\nUPDATE Task:\n{"op":"update","entity":"task","id":"<exact id>","ifUpdatedAt":"<exact timestamp>","changes":{"plannedDate":"2026-08-24","estimatedMinutes":60}}\nDELETE Task:\n{"op":"delete","entity":"task","id":"<exact id>","ifUpdatedAt":"<exact timestamp>","reason":"No longer needed"}\nCREATE Project:\n{"op":"create","entity":"project","value":{"ref":"new-project","name":"New Project","type":"standard","description":"","favorite":false}}\n\nCURRENT PLANNER CONTEXT (local copy; do not invent anything not present):\n${JSON.stringify({ projects, tasks, habits, timeBlocks, recurringSeries }, null, 2)}\n\nReturn JSON only. Keep the patch as small as possible: do not rewrite fields whose values should stay unchanged.`
}
